---

# Documentation:
# https://github.com/geerlingguy/ansible-role-certbot


- hosts: all
  become: yes
  gather_facts: yes

  vars:
    certbot_auto_renew_user: root
    certbot_create_if_missing: true
    certbot_admin_email: email@example.com
    certbot_auto_renew_options: '--quiet --no-self-upgrade
    --pre-hook "service nginx stop" --post-hook "service nginx start"'
    certbot_create_standalone_stop_services: []

    certbot_certs:
      - domains:
        - "{{ inventory_hostname }}"

  tasks:
  - name: Include vars from local-configure.yml if found
    include_vars: "{{ item }}"
    with_first_found:
     - local-configure.yml
     - null.yml

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install dependencies (RedHat).
      yum: name={{ item }} state=present
      when: ansible_os_family == 'RedHat'
      with_items:
        - cronie
        - epel-release

    - name: Install cron (Debian).
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.certbot
