---

- src: https://github.com/plone/ansible.plone_server.git
  version: 3aab6e314a89eed872242a39ba18950d7f0a2dc3
  name: plone.plone_server

- src: https://github.com/jnv/ansible-role-unattended-upgrades.git
  version: v1.5.0
  name: jnv.unattended-upgrades
