---


- name: Fail if no administrative email set
  fail:
    msg: "You must set the admin_email variable."
  when: not admin_email

- include: "{{ ansible_os_family }}.yml"

- name: "Generate new certificates as necessary"
  shell: >
    certbot certonly --nginx --email '{{ admin_email }}'
    --non-interactive
    --agree-tos -d '{{ item }}'
    {% if certbot_staging %} --staging {% endif %}
  args:
    creates: "/etc/letsencrypt/live/{{ item }}/cert.pem"
  loop: "{{ certbot_hosts }}"

- name: "Test renewal with a dry run."
  shell: >
    certbot renew --dry-run --nginx
