#!/usr/bin/env python

# munin plugin to gather resident-size for
# all specified user ids.

import os
import re
import sys
import subprocess

users = os.environ.get('users') or 'plone_daemon'
category = os.environ.get('category') or 'plone'

ps_command = 'ps -ww -o rss= -o command= -U %s' % users
# print ps_command
command_re = re.compile(r'\s(\S+)(\.conf| fg)')
pid_split = re.compile(r'^(\d+) +(.+)$')

config = len(sys.argv) > 1 and sys.argv[1].lower() == 'config'
if config:
    print "graph_title %s resident memory" % users
    print "graph_vlabel MB"
    print "graph_category %s" % category
    print "graph_scale no"

ps_out = subprocess.Popen(
    ps_command.split(),
    stdout=subprocess.PIPE
    ).stdout.read()

for line in ps_out.split('\n'):
    # print line
    match = pid_split.match(line)
    if match:
        res, command = match.groups()
        # print res, command
        cmatch = command_re.search(command)
        if cmatch:
            cstr = cmatch.groups()[0].replace('/', '_'
                ).replace('-', '_'
                ).replace('.', '_'
                ).replace('_zope', ''
                ).replace('_etc', ''
                ).strip('_'
                ).lower().split('_')[-1]
            if config:
                print "%s.label %s" % (cstr, cstr)
            else:
                print "%s.value %d" % (cstr, int(res) / 1024)
