---

# Set target server timezone from 'timezone' variable.
# Works on systems with timedatectl.

- name: Look for timedatectl
  shell: "which timedatectl"
  ignore_errors: yes
  register: which_timedatectl

- name: "Set timezone to {{ timezone }}"
  shell: 'timedatectl set-timezone "{{ timezone }}"'
  when: which_timedatectl.rc == 0

- debug: msg="We don't know how to set timezone in systems without timedatectl. You'll need to do it yourself."
  when: which_timedatectl.rc > 0
